'use strict';
const base=window.EXPLORER_DATA, storageKey='rap-ai-explorer-v1';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const statuses=['Operational','Developing','Pilot/Experimental','Governance','Adjacent/Research','Not established'];
let examples=structuredClone(base.examples),view='examples',editing=false,editingId=null,storageAvailable=true;
function message(t){$('#message').textContent=t;}
try{const saved=localStorage.getItem(storageKey);if(saved){const parsed=JSON.parse(saved);if(parsed.schemaVersion!==1||!Array.isArray(parsed.examples)||!parsed.examples.every(e=>e.id&&e.tool&&Array.isArray(e.audience)&&Array.isArray(e.sources)&&base.categories.includes(e.category)))throw Error('Invalid data');examples=parsed.examples.map(e=>e.origin==='Research document'?(structuredClone(base.examples.find(b=>b.id===e.id))||e):e);if(parsed.dataRevision!==base.dataRevision)message('Research has been updated. Original entries were refreshed; your locally edited entries and deletions were kept.');}}catch(e){storageAvailable=false;message('Saved browser data could not be read. Original research is shown. Edits can be exported as JSON.');}
function save(){try{localStorage.setItem(storageKey,JSON.stringify({schemaVersion:1,dataRevision:base.dataRevision,examples}));storageAvailable=true;message('Saved automatically in this browser. Use Export JSON for a portable backup.');}catch(e){message('Browser storage is unavailable. Changes last only for this session. Export JSON to keep a backup.');}}
function options(select,values,all){const previous=select.value;select.innerHTML=(all?'<option value="">'+esc(all)+'</option>':'')+values.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');if(values.includes(previous))select.value=previous;}
function populate(){options($('#category'),base.categories,'All categories');for(const key of ['regulator','country','audience','status']){const values=key==='audience'?['Internal','Public-facing','Sector-facing','Not established']:key==='status'?statuses:[...new Set(examples.map(e=>e[key]))].sort();options($('#'+key),values,'All '+({regulator:'regulators',country:'regions',audience:'audiences',status:'statuses'}[key]));}$('#total').textContent=examples.length;}
function sourceLinks(e){return e.sources.map(s=>{let valid=false;try{valid=['https:','http:'].includes(new URL(s.url).protocol);}catch{}return valid?`<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.label||'Source')} (opens in new tab)</a>`:esc(s.label||'No valid link supplied');}).join('<br>')||'No link provided in the document.';}
function card(e){return `<article class="card"><p class="meta">${esc(e.country)}</p><span class="badge" data-status="${esc(e.status)}">${esc(e.status)}</span><h3>${esc(e.tool)}</h3><div class="regulator">${esc(e.regulator)}</div><p>${esc(e.description)}</p><details><summary>Explore details</summary><h4>Relevance for regulators</h4><p>${esc(e.usp)}</p><p class="editorial-note">Practical interpretation, not a measured benefit.</p>${e.regulatorQuestion?`<h4>Question to ask before adopting</h4><p>${esc(e.regulatorQuestion)}</p>`:''}<h4>Status & evidence</h4><p>${esc(e.statusNote)}</p><h4>Audience</h4><p>${esc(e.audience.join(' · ')||'Not established by the reviewed sources')}</p><h4>Source</h4><p>${sourceLinks(e)}</p><p>${esc(e.sourceRef)}</p><p>${esc(e.origin==='Reviewed research'?(e.evidenceLabel||'Reviewed research')+' · Reviewed '+e.reviewedDate:e.origin==='Research document'?'Original document entry; not updated':'Locally added or edited entry; review its evidence before use')}</p></details>${editing?`<div class="card-actions"><button data-edit="${esc(e.id)}">Edit</button><button class="delete" data-delete="${esc(e.id)}">Delete</button></div>`:''}</article>`;}
function renderCards(){const isExample=view==='examples',isRisk=view==='risks';$('#filter-panel').hidden=isRisk;$$('.example-filter').forEach(e=>e.hidden=!isExample);$('#add').hidden=!(editing&&isExample);$('#export').hidden=!editing;$('#import').hidden=!editing;$('#edit-notice').hidden=!editing;$$('nav button').forEach(b=>{if(b.dataset.view===view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});$('#view-title').textContent=isExample?'AI in practice':isRisk?'Human judgement stays central':'Where AI could help';$('#view-description').textContent=isExample?'Concrete and experimental examples, grouped by what they support.':isRisk?'Risks and safeguards identified in the research.':'Potential applications, not claims of deployment.';
if(isRisk){$('#count').textContent=base.risks.length+' risk areas';$('#results').innerHTML='<div class="principle">AI can support preparatory, analytical and administrative work. Humans remain responsible for judgement, interpretation and decisions.</div><div class="grid">'+base.risks.map((r,i)=>`<article class="card"><p class="meta">Safeguard ${String(i+1).padStart(2,'0')}</p><h3>${esc(r.title)}</h3><p>${esc(r.why)}</p><div class="risk-box"><strong>What regulators can do</strong>${esc(r.action)}</div></article>`).join('')+'</div>';return;}
const q=$('#search').value.trim().toLowerCase();const list=(isExample?examples:base.usecases).filter(e=>(!q||JSON.stringify(e).toLowerCase().includes(q))&&(!$('#category').value||e.category===$('#category').value)&&(!isExample||['regulator','country','status','audience'].every(k=>!$('#'+k).value||(k==='audience'?(e.audience.length?e.audience:['Not established']).includes($('#'+k).value):e[k]===$('#'+k).value))));$('#count').textContent=list.length+' of '+(isExample?examples.length:base.usecases.length)+(isExample?' examples':' use cases');
$('#results').innerHTML=list.length?base.categories.map(c=>{const rows=list.filter(e=>e.category===c);return rows.length?`<h3 class="category-heading">${esc(c)} <span>${rows.length}</span></h3><p class="category-description">${esc(base.categoryDescriptions?.[c]||'')}</p><div class="grid">${rows.map(e=>isExample?card(e):`<article class="card"><h3>${esc(e.title)}</h3><p>${esc(e.description)}</p><div class="risk-box"><strong>Key risk</strong>${esc(e.risk)}</div></article>`).join('')}</div>`:'';}).join(''):'<div class="empty"><h3>No matching results</h3><p>Try another term or clear the filters.</p></div>';}
function openEditor(id){editingId=id||null;const form=$('#edit-form');form.reset();form.elements.sourceUrl.setCustomValidity('');options(form.elements.category,base.categories);options(form.elements.status,statuses);const e=id?examples.find(e=>e.id===id):{status:'Not established',sourceRef:'Locally added example; provide source details.'};for(const key of ['tool','regulator','country','category','status','description','usp','statusNote','sourceRef','regulatorQuestion'])if(e[key])form.elements[key].value=e[key];$$('input[name="audience"]').forEach(c=>c.checked=(e.audience||[]).includes(c.value));form.elements.sourceLabel.value=e.sources?.[0]?.label||'';form.elements.sourceUrl.value=e.sources?.[0]?.url||'';$('#editor-title').textContent=id?'Edit example':'Add example';$('#editor').showModal();form.elements.tool.focus();}
$$('nav button').forEach(b=>b.addEventListener('click',()=>{view=b.dataset.view;render();}));$('#search').addEventListener('input',render);$$('.filters select').forEach(s=>s.addEventListener('change',render));$('#clear').onclick=()=>{$('#search').value='';$$('.filters select').forEach(s=>s.value='');render();};$('#edit-toggle').onclick=()=>{editing=!editing;$('#edit-toggle').setAttribute('aria-pressed',editing);$('#edit-toggle span').textContent=editing?'On':'Off';renderCards();};$('#add').onclick=()=>openEditor();$('#close').onclick=$('#cancel').onclick=()=>$('#editor').close();
$('#results').addEventListener('click',event=>{const button=event.target.closest('button');if(!button||!editing)return;if(button.dataset.edit)openEditor(button.dataset.edit);if(button.dataset.delete){const e=examples.find(e=>e.id===button.dataset.delete);if(confirm('Delete “'+e.tool+'” from this browser’s collection?')){examples=examples.filter(x=>x.id!==e.id);save();populate();render();}}});
$('#edit-form').addEventListener('submit',event=>{event.preventDefault();const f=new FormData(event.target);const url=String(f.get('sourceUrl')).trim();if(url&&!/^https?:\/\//i.test(url)){event.target.elements.sourceUrl.setCustomValidity('Use an http:// or https:// source URL.');event.target.elements.sourceUrl.reportValidity();return;}const prior=editingId?examples.find(e=>e.id===editingId):null;const entry={...prior,id:editingId||'local-'+Date.now()+'-'+Math.random().toString(36).slice(2),origin:'Local edit'};for(const key of ['tool','regulator','country','category','status','description','usp','statusNote','sourceRef']){entry[key]=String(f.get(key)).trim();if(!entry[key]){event.target.elements[key].focus();return;}}entry.regulatorQuestion=String(f.get('regulatorQuestion')||'').trim();entry.audience=f.getAll('audience');entry.sources=[...(url?[{label:String(f.get('sourceLabel')).trim()||'Source',url}]:[]),...(prior?.sources?.slice(1)||[])];if(editingId)examples=examples.map(e=>e.id===editingId?entry:e);else examples.push(entry);save();populate();$('#editor').close();render();});$('#edit-form').elements.sourceUrl.oninput=event=>event.target.setCustomValidity('');
$('#export').onclick=()=>{const blob=new Blob([JSON.stringify({...base,examples},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download='ai-energy-explorer-data.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);message('JSON backup exported. It includes the current examples, potential use cases and risks.');};

let presentation='map',mapScale=1,mapX=0,mapY=0,mapWidth=1800,mapHeight=1300,overviewScale=1,focusedArea=null;let branchBounds={};
const palette=['#007f83','#6079a7','#bb7148','#7c6c9e','#548a68','#ad8152','#82709d','#497d99'];
function filteredRecords(){const q=$('#search').value.trim().toLowerCase();return (view==='examples'?examples:base.usecases).filter(e=>(!q||JSON.stringify(e).toLowerCase().includes(q))&&(!$('#category').value||e.category===$('#category').value)&&(view!=='examples'||['regulator','country','status','audience'].every(k=>!$('#'+k).value||(k==='audience'?(e.audience.length?e.audience:['Not established']).includes($('#'+k).value):e[k]===$('#'+k).value))));}
function render(){focusedArea=null;showArea(null);renderCards();drawMap();}
function transformMap(){$('#map-world').style.transform=`translate(${mapX}px,${mapY}px) scale(${mapScale})`;}
function fitMap(){const rect=$('#map-viewport').getBoundingClientRect();if(!rect.width||!rect.height)return;mapScale=Math.min(1,(rect.width-36)/mapWidth,(rect.height-105)/mapHeight);mapScale=Math.max(.12,mapScale);overviewScale=mapScale;mapX=(rect.width-mapWidth*mapScale)/2;mapY=(rect.height-mapHeight*mapScale)/2;transformMap();}
function showArea(name){const panel=$('#area-explainer');panel.hidden=!name;$('#area-title').textContent=name||'';$('#area-description').textContent=base.categoryDescriptions?.[name]||'';}
function returnToOverview(){focusedArea=null;showArea(null);if($('#category').value){$('#category').value='';renderCards();drawMap();}else fitMap();}
function focusArea(name){const b=branchBounds[name];if(!b)return;focusedArea=name;showArea(name);$('#filter-panel').scrollTop=0;const r=$('#map-viewport').getBoundingClientRect();mapScale=Math.max(.12,Math.min(1.35,(r.width-48)/b.width,(r.height-105)/b.height));mapX=r.width/2-b.x*mapScale;mapY=(r.height-50)/2-b.y*mapScale;transformMap();}
function zoomMap(factor,anchor){const r=$('#map-viewport').getBoundingClientRect();const next=Math.max(.12,Math.min(2,mapScale*factor));if(factor<1&&(focusedArea||$('#category').value)&&next<=overviewScale*1.15){returnToOverview();return;}const x=anchor?.x??r.width/2,y=anchor?.y??r.height/2;mapX=x-(x-mapX)*next/mapScale;mapY=y-(y-mapY)*next/mapScale;mapScale=next;transformMap();}
function drawMap(){if(presentation!=='map')return;branchBounds={};const records=view==='risks'?base.risks:filteredRecords();let groups=view==='risks'?[{name:'Risks & Governance',rows:records}]:base.categories.map(name=>({name,rows:records.filter(e=>e.category===name)})).filter(g=>g.rows.length||(!$('#category').value&&!$('#search').value&&view==='examples'));const left=[],right=[];let lh=0,rh=0;for(const g of groups){g.height=Math.max(135,g.rows.length*140);if(lh<=rh){left.push(g);lh+=g.height+50;}else{right.push(g);rh+=g.height+50;}}mapHeight=Math.max(550,lh,rh)+80;mapWidth=1800;const center={x:900,y:mapHeight/2};const world=$('#map-world');world.style.width=mapWidth+'px';world.style.height=mapHeight+'px';const canvas=$('#connections');canvas.width=mapWidth;canvas.height=mapHeight;const ctx=canvas.getContext('2d');const nodes=[];function node(x,y,label,sub,kind,key,color){nodes.push(`<button class="map-node ${kind}" style="left:${x}px;top:${y}px;--branch:${color||'#007f83'}" data-kind="${kind}" data-key="${esc(key)}">${esc(label)}<small>${esc(sub)}</small></button>`);}function line(x1,y1,x2,y2,color){ctx.beginPath();ctx.moveTo(x1,y1);ctx.bezierCurveTo((x1+x2)/2,y1,(x1+x2)/2,y2,x2,y2);ctx.strokeStyle=color;ctx.lineWidth=2;ctx.stroke();}node(center.x,center.y,'AI in Energy Regulation',view==='risks'?'Human judgement stays central':records.length+(view==='examples'?' research examples':' potential use cases'),'root','');
for(const [side,total] of [[left,lh],[right,rh]]){const isLeft=side===left;let top=(mapHeight-total+50)/2;for(const g of side){const color=palette[Math.max(0,base.categories.indexOf(g.name))%palette.length];const gx=isLeft?570:1230,gy=top+g.height/2;branchBounds[g.name]={x:isLeft?355:1445,y:gy,width:710,height:Math.max(250,g.height+30)};line(center.x,center.y,gx,gy,color+'90');node(gx,gy,g.name,g.rows.length+(view==='examples'?' examples':view==='risks'?' safeguards':' opportunities'),'category',g.name,color);g.rows.forEach((e,i)=>{const x=isLeft?190:1610,y=top+70+i*140;line(gx,gy,x,y,color+'80');node(x,y,e.tool||e.title,e.country?e.country+' · '+e.status:view==='risks'?'View safeguard':'View opportunity & risk','record',e.id||e.title,color);});top+=g.height+50;}}
$('#map-nodes').innerHTML=records.length?nodes.join(''):'<div class="empty"><h3>No matching records</h3><p>Clear the filters to explore the full map.</p></div>';fitMap();}
function setPresentation(next){presentation=next;document.body.classList.toggle('map-mode',next==='map');$('#map-view').setAttribute('aria-pressed',next==='map');$('#cards-view').setAttribute('aria-pressed',next==='cards');if(next==='map'){focusedArea=null;showArea(null);drawMap();}}
$('#map-view').onclick=()=>setPresentation('map');$('#cards-view').onclick=()=>setPresentation('cards');$('#zoom-in').onclick=()=>zoomMap(1.3);$('#zoom-out').onclick=()=>zoomMap(1/1.3);$('#map-fit').onclick=returnToOverview;$('#area-back').onclick=returnToOverview;
$('#map-nodes').onclick=event=>{const n=event.target.closest('button');if(!n)return;if(n.dataset.kind==='root'){returnToOverview();return;}if(n.dataset.kind==='category'){if(view!=='risks')focusArea(n.dataset.key);return;}const e=(view==='examples'?examples:view==='risks'?base.risks:base.usecases).find(e=>(e.id||e.title)===n.dataset.key);if(!e)return;$('#record-content').innerHTML=view==='examples'?card(e):`<article class="card"><p class="meta">${esc(view==='risks'?'Risks & Governance':e.category)}</p><h3>${esc(e.title)}</h3><p>${esc(e.description||e.why)}</p><div class="risk-box"><strong>${view==='risks'?'What regulators can do':'Key risk'}</strong>${esc(e.risk||e.action)}</div><p class="meta">Source: AI research.docx</p></article>`;const details=$('#record-content details');if(details)details.open=true;$('#record-dialog').showModal();};$('#record-close').onclick=()=>$('#record-dialog').close();
$('#record-content').onclick=event=>{const b=event.target.closest('button');if(!b)return;if(b.dataset.edit){$('#record-dialog').close();openEditor(b.dataset.edit);}if(b.dataset.delete){const e=examples.find(e=>e.id===b.dataset.delete);if(confirm('Delete “'+e.tool+'” from this browser’s collection?')){examples=examples.filter(x=>x.id!==e.id);save();populate();$('#record-dialog').close();render();}}};
let drag=null;$('#map-viewport').onpointerdown=event=>{if(event.target.closest('button'))return;drag={x:event.clientX,y:event.clientY,ox:mapX,oy:mapY};$('#map-viewport').setPointerCapture(event.pointerId);};$('#map-viewport').onpointermove=event=>{if(!drag)return;mapX=drag.ox+event.clientX-drag.x;mapY=drag.oy+event.clientY-drag.y;transformMap();};$('#map-viewport').onpointerup=$('#map-viewport').onpointercancel=()=>drag=null;$('#map-viewport').onkeydown=event=>{if(event.target.closest('button'))return;const moves={ArrowLeft:[50,0],ArrowRight:[-50,0],ArrowUp:[0,50],ArrowDown:[0,-50]};if(moves[event.key]){event.preventDefault();mapX+=moves[event.key][0];mapY+=moves[event.key][1];transformMap();}if(['+','=','-'].includes(event.key)){event.preventDefault();zoomMap(event.key==='-'?1/1.3:1.3);}};
$('#map-nodes').addEventListener('focusin',event=>{const b=event.target.closest('button');if(!b)return;const r=b.getBoundingClientRect(),v=$('#map-viewport').getBoundingClientRect();if(r.left<v.left||r.right>v.right||r.top<v.top||r.bottom>v.bottom){mapX+=(v.left+v.right-r.left-r.right)/2;mapY+=(v.top+v.bottom-r.top-r.bottom)/2;transformMap();}});
window.addEventListener('resize',()=>{if(presentation==='map'){if(focusedArea)focusArea(focusedArea);else fitMap();}});
$('#map-viewport').addEventListener('wheel',event=>{if(event.ctrlKey||event.metaKey)return;event.preventDefault();const rect=$('#map-viewport').getBoundingClientRect();const units=event.deltaMode===1?16:event.deltaMode===2?rect.height:1;const delta=Math.max(-160,Math.min(160,event.deltaY*units));zoomMap(Math.exp(-delta*.0025),{x:event.clientX-rect.left,y:event.clientY-rect.top});},{passive:false});
function validateImport(data){if(!data||data.schemaVersion!==1||!Array.isArray(data.examples)||data.examples.length>1000)throw Error('Expected an Explorer JSON backup with schemaVersion 1.');const ids=new Set();for(const e of data.examples){if(!e||['id','tool','regulator','country','category','status','description','usp','statusNote','sourceRef'].some(k=>typeof e[k]!=='string'||!e[k].trim()||e[k].length>20000)||!base.categories.includes(e.category)||!statuses.includes(e.status)||ids.has(e.id)||!Array.isArray(e.audience)||e.audience.some(a=>!['Internal','Public-facing','Sector-facing'].includes(a))||!Array.isArray(e.sources)||e.sources.some(s=>!s||typeof s.label!=='string'||typeof s.url!=='string'||!/^https?:\/\//i.test(s.url)))throw Error('The backup contains incomplete or unsupported example data.');ids.add(e.id);}return data.examples;}
$('#import').onclick=()=>$('#import-file').click();$('#import-file').onchange=async event=>{const file=event.target.files[0];if(!file)return;try{if(file.size>5000000)throw Error('Choose an Explorer JSON backup smaller than 5 MB.');const rows=validateImport(JSON.parse(await file.text()));if(!confirm(`Replace the current ${examples.length} examples with ${rows.length} examples from this backup? Export first if you want to keep the current collection.`))return;examples=rows.map(e=>e.origin==='Research document'?(structuredClone(base.examples.find(b=>b.id===e.id))||e):e);save();populate();render();}catch(error){message('Import failed: '+error.message+' Your current data is unchanged.');}finally{event.target.value='';}};
populate();render();
